DROP TABLE IF EXISTS actor;

DROP TABLE IF EXISTS category;

DROP TABLE IF EXISTS country;

DROP TABLE IF EXISTS city;

DROP TABLE IF EXISTS address;

DROP TABLE IF EXISTS language;

DROP TABLE IF EXISTS film;

DROP TABLE IF EXISTS film_actor;

DROP TABLE IF EXISTS film_category;

DROP TABLE IF EXISTS staff;

DROP TABLE IF EXISTS store;

DROP TABLE IF EXISTS customer;

DROP TABLE IF EXISTS inventory;

DROP TABLE IF EXISTS rental;

DROP TABLE IF EXISTS payment;
