CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE EXTENSION IF NOT EXISTS plpgsql;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS public;

CREATE TYPE mpaa_rating AS ENUM ('G', 'PG', 'PG-13', 'R', 'NC-17');

CREATE DOMAIN year AS integer CONSTRAINT year_check CHECK (VALUE >= 1901 AND VALUE <= 2155);

CREATE TABLE actor (
    actor_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,first_name VARCHAR(45) NOT NULL
    ,last_name VARCHAR(45) NOT NULL
    ,full_name TEXT GENERATED ALWAYS AS ((first_name::text || ' '::text) || last_name::text) STORED
    ,full_name_reversed TEXT GENERATED ALWAYS AS ((last_name::text || ' '::text) || first_name::text) STORED
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE address (
    address_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,address VARCHAR(50) NOT NULL
    ,address2 VARCHAR(50)
    ,district VARCHAR(20) NOT NULL
    ,city_id INT NOT NULL
    ,postal_code VARCHAR(10)
    ,phone TEXT NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE category (
    category_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,name VARCHAR(45) NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE city (
    city_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,city VARCHAR(50) NOT NULL
    ,country_id INT NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE country (
    country_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,country VARCHAR(50) NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer (
    customer_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,store_id INT NOT NULL
    ,first_name VARCHAR(45) NOT NULL
    ,last_name VARCHAR(45) NOT NULL
    ,email VARCHAR(50)
    ,address_id INT NOT NULL
    ,active BOOLEAN NOT NULL DEFAULT true
    ,create_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE department (
    department_id UUID NOT NULL
    ,name VARCHAR(255) NOT NULL
);

CREATE TABLE employee (
    employee_id UUID NOT NULL
    ,name VARCHAR(255) NOT NULL
    ,title VARCHAR(255) NOT NULL
    ,manager_id UUID
);

CREATE TABLE employee_department (
    employee_id UUID NOT NULL
    ,department_id UUID NOT NULL
);

CREATE TABLE film (
    film_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,title TEXT NOT NULL
    ,description TEXT
    ,release_year year
    ,language_id INT NOT NULL
    ,original_language_id INT
    ,rental_duration INT NOT NULL DEFAULT 3
    ,rental_rate NUMERIC(4,2) NOT NULL DEFAULT 4.99
    ,length INT
    ,replacement_cost NUMERIC(5,2) NOT NULL DEFAULT 19.99
    ,rating mpaa_rating DEFAULT 'G'::mpaa_rating
    ,special_features TEXT[]
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,fulltext TSVECTOR
);

CREATE TABLE film_actor (
    actor_id INT NOT NULL
    ,film_id INT NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE film_category (
    film_id INT NOT NULL
    ,category_id INT NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory (
    inventory_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,film_id INT NOT NULL
    ,store_id INT NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE language (
    language_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,name TEXT NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment (
    payment_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,customer_id INT NOT NULL
    ,staff_id INT NOT NULL
    ,rental_id INT
    ,amount NUMERIC(5,2) NOT NULL
    ,payment_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rental (
    rental_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,rental_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,inventory_id INT NOT NULL
    ,customer_id INT NOT NULL
    ,return_date TIMESTAMPTZ
    ,staff_id INT NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE staff (
    staff_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,first_name VARCHAR(45) NOT NULL
    ,last_name VARCHAR(45) NOT NULL
    ,address_id INT NOT NULL
    ,picture BYTEA
    ,email VARCHAR(50)
    ,store_id INT
    ,active BOOLEAN NOT NULL DEFAULT true
    ,username VARCHAR(16) NOT NULL
    ,password VARCHAR(40)
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE store (
    store_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    ,manager_staff_id INT NOT NULL
    ,address_id INT NOT NULL
    ,last_update TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE task (
    task_id UUID NOT NULL
    ,employee_id UUID NOT NULL
    ,department_id UUID NOT NULL
    ,task VARCHAR(255) NOT NULL
    ,data JSONB
);
